# Gitlab CI Configuration File
# © 2023 Fentech <diviyan@fentech.ai>
exclude: '.semgrep|tests'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-added-large-files
    # -   id: detect-aws-credentials
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
# -   repo: https://github.com/fentech-ai/commit-checks
#     rev: 0.1.7
#     hooks:
#     - id: check-variable-names
#     - id: check-print
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
        - --recursive
        - --in-place
        - --remove-all-unused-imports
        - --remove-unused-variables
        - --expand-star-imports
        - --exclude
        - __init__.py
        - --remove-duplicate-keys
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        args: ["--ignore=D401,D213,D211,D400,D413,D203"]
        additional_dependencies: ["tomli"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        args: [
            "--config-file=pyproject.toml",
            --no-strict-optional,
            --ignore-missing-imports,
            --install-types,
            --explicit-package-bases,
            "--follow-imports=silent"
        ]
        additional_dependencies: [pandas-stubs, numpy, types-requests, types-PyYAML, types-requests]